// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzTZEDvSPoOj0sXX331Np0AVWMJXLUdLQ',
    appId: '1:59267060940:web:36bd1baf8ead16b5811e69',
    messagingSenderId: '59267060940',
    projectId: 'fooddeliverytute-baf35',
    authDomain: 'fooddeliverytute-baf35.firebaseapp.com',
    storageBucket: 'fooddeliverytute-baf35.appspot.com',
    measurementId: 'G-XGFML92HGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDejZCWjIF5qdXhzXyZrnhHdXJD4rbQww8',
    appId: '1:59267060940:android:aea7049f1d710b00811e69',
    messagingSenderId: '59267060940',
    projectId: 'fooddeliverytute-baf35',
    storageBucket: 'fooddeliverytute-baf35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcmsfPewLgkXSW7zscA-V9nfayjpIjD6M',
    appId: '1:59267060940:ios:c72ae21f58cf1600811e69',
    messagingSenderId: '59267060940',
    projectId: 'fooddeliverytute-baf35',
    storageBucket: 'fooddeliverytute-baf35.appspot.com',
    iosBundleId: 'com.example.onlineFoodOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcmsfPewLgkXSW7zscA-V9nfayjpIjD6M',
    appId: '1:59267060940:ios:c72ae21f58cf1600811e69',
    messagingSenderId: '59267060940',
    projectId: 'fooddeliverytute-baf35',
    storageBucket: 'fooddeliverytute-baf35.appspot.com',
    iosBundleId: 'com.example.onlineFoodOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzTZEDvSPoOj0sXX331Np0AVWMJXLUdLQ',
    appId: '1:59267060940:web:bbc6b6c5b7afeac8811e69',
    messagingSenderId: '59267060940',
    projectId: 'fooddeliverytute-baf35',
    authDomain: 'fooddeliverytute-baf35.firebaseapp.com',
    storageBucket: 'fooddeliverytute-baf35.appspot.com',
    measurementId: 'G-HSRJ0C95S9',
  );
}
